services:
  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    volumes:
     - postgres:/var/lib/postgresql/data
  appair:
    image: cosmtrek/air
    working_dir: /monke
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./:/monke
#  app:
#    build: .
#    restart: always
#    env_file:
#      - .env
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
